config/routes.rb
require 'sessions_helper'

SciRate::Application.routes.draw do
  root 'feeds#index'

  get '/search', to: 'papers#search', as: 'papers_search'

  post '/api/scite/:paper_uid', to: 'api#scite',
       as: :scite, paper_uid: /.+/
  post '/api/unscite/:paper_uid', to: 'api#unscite',
       as: :unscite, paper_uid: /.+/
  post '/api/subscribe/:feed_uid', to: 'api#subscribe',
       as: :subscribe, feed_uid: /.+/
  post '/api/unsubscribe/:feed_uid', to: 'api#unsubscribe',
       as: :unsubscribe, feed_uid: /.+/
  post '/api/hide_from_recent/:comment_id', to: 'api#hide_from_recent',
       as: :hide_from_recent
  post '/api/settings', to: 'api#settings'

  post '/api/resend_confirm', to: 'api#resend_confirm', as: :resend_confirm

  resources :comments do
    member do
      post :edit
      post :delete
      post :restore
      post :upvote
      post :downvote
      post :unvote
      post :report
      post :unreport
      post :reply
    end
  end
  get '/comments', to: 'comments#index'
  get '/comments/:id/history', to: 'comments#history', as: 'comment_history'

  get '/auth/:provider/callback', to: 'sessions#omniauth_callback'
  get '/auth/:provider/disconnect',
    to: 'sessions#omniauth_disconnect', as: 'omniauth_disconnect'
  get '/auth/failure', to: 'sessions#omniauth_failure', as: 'omniauth_failure'
  post '/auth/create', to: 'sessions#omniauth_create', as: 'omniauth_create'

  get '/signup',   to: 'users#new', as: 'signup'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',   to: 'sessions#destroy'
  get '/signin',   to: redirect('/login')
  get '/signout',  to: redirect('/logout')

  get '/about',    to: 'static_pages#about'
  get '/legal',    to: 'static_pages#legal'
  get '/moderation',    to: 'static_pages#moderation'

  get '/reset_password', to: 'password_resets#new', as: :reset_password
  post '/reset_password', to: 'password_resets#create'

  get '/reset_password/:id', to: 'password_resets#confirm', as: :reset_password_confirm
  post '/reset_password/:id', to: 'password_resets#submit'

  get '/settings', to: 'users#settings'
  post '/settings', to: 'users#settings'

  get '/settings/password', to: 'users#settings_password'
  post '/settings/password', to: 'users#settings_password'

  #resources :users, only: [:new, :create, :edit, :update, :destroy, :admin]
  get '/users/:id/subscriptions', to: 'users#subscriptions', as: 'subscriptions_user'
  get '/users/:id/activate/:confirmation_token', to: 'users#activate', as: 'activate_user'
  get '/feeds', to: 'users#feeds', as: 'feeds'

  get '/arxiv/:paper_uid/scites', to: 'papers#scites', paper_uid: /(.+\/.+|\d+.\d+)(v\d)?/, as: 'paper_scites'
  get '/arxiv/:feed/comments', to: 'comments#index', feed: /.+/, as: 'feed_comments'
  get '/arxiv/*paper_uid', to: 'papers#show', paper_uid: /.+\/.+|\d+.\d+(v\d)?/, as: 'paper'
  get '/arxiv/:feed', to: 'feeds#show', feed: /.+/, as: 'feed'#, constraints: NeedsUserConstraint

  get '/admin', to: 'admin/base#index', as: 'admin'
  post '/admin/alert', to: 'admin/base#alert', as: 'admin_alert'

  get '/admin/users/:username/edit', to: 'admin/users#edit', as: 'admin_edit_user'
  post '/admin/users/:username/update', to: 'admin/users#update', as: 'admin_update_user'
  post '/admin/users/:username/become', to: 'admin/users#become', as: 'admin_become_user'

  get '/:username/scites', to: 'users#scites', username: /.+/, as: 'user_scites'
  get '/:username/comments', to: 'users#comments', username: /.+/, as: 'user_comments'
  get '/:username/papers', to: 'users#papers', username: /.+/, as: 'user_papers'
  get '/:username', to: 'users#activity', username: /.+/, as: 'user'
end

app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id                  :integer          not null, primary key
#  uid                 :text             not null
#  source              :text             not null
#  fullname            :text             not null
#  position            :integer          default(0), not null
#  subscriptions_count :integer          default(0), not null
#  last_paper_date     :datetime
#  parent_uid          :text
#

class Feed < ActiveRecord::Base
  belongs_to :parent, foreign_key: :parent_uid,
             primary_key: :uid, class_name: "Feed"
  has_many :children, foreign_key: :parent_uid,
           primary_key: :uid, class_name: 'Feed'
  has_many :subscriptions, dependent: :destroy,
           foreign_key: :feed_uid, primary_key: :uid
  has_many :users, through: :subscriptions
  has_many :categories, dependent: :destroy,
           foreign_key: :feed_uid, primary_key: :uid
  has_many :papers, through: :categories, source: :paper

  validates :uid, presence: true, uniqueness: true
  validates :fullname, presence: true
  validates :source, presence: true

  # Returns toplevel arxiv categories for sidebar
  def self.arxiv_folders
    @@arxiv_folders ||= Feed.where(uid: Settings::ARXIV_FOLDERS).includes(:children).to_a
  end

  def self.arxiv_import(uids, opts={})
    existing = Feed.all.map(&:uid)

    columns = [:uid, :fullname, :source]
    values = []

    (uids - existing).map do |uid|
      logger.info "Discovered new feed: #{uid}"
      values << [
        uid,
        uid.to_s,
        "arxiv"
      ]
    end

    result = Feed.import(columns, values, opts)
    unless result.failed_instances.empty?
      SciRate.notify_error("Error importing feeds: #{result.failed_instances.inspect}")
    end
  end

  def self.find_related_uids(uids)
    Rails.cache.fetch [:related_uids, uids] do
      uids + Feed.where(parent_uid: uids).pluck(:uid)
    end
  end

  # Grab a set of feeds in order by uid
  def self.in_order(uids)
    Feed.where(uid: uids).includes(:children).index_by(&:uid).slice(*uids).values
  end

  def to_param
    uid
  end

  # Update last_paper_date to the given timestamp if applicable
  # Also update parent
  def new_paper_date!(dt)
    if self.last_paper_date.nil? || dt.to_date > self.last_paper_date.to_date
      self.last_paper_date = dt
      self.save!

      unless self.parent_uid.nil?
        self.parent.new_paper_date!(dt)
      end
    end
  end

  def update_last_paper_date!
    uids = [self.uid] + self.children.pluck(:uid)
    category = Category.where(feed_uid: uids).order("crosslist_date ASC").last
    unless category.nil?
      self.last_paper_date = category.crosslist_date
      self.save!
    end
  end
end

app/controllers/feeds_controller.rb
require 'data_helpers'

class FeedsController < ApplicationController
  before_filter :parse_params

  # No user, and no feed specified: show all papers
  def index_nouser
    if @date.nil?
      @date = Feed.order("last_paper_date DESC").limit(1).pluck(:last_paper_date).first
    end

    @backdate = _backdate(@date, @range)
    @recent_comments = _recent_comments
    @papers, @pagination = _range_query(nil, @backdate, @date, @page)

    render 'feeds/show'
  end

  # Aggregated index feed
  def index
    return index_nouser unless signed_in?

    feed_uids = Rails.cache.fetch [:index_uids, current_user] do
      uids = current_user.subscriptions.pluck(:feed_uid)
      uids.concat Feed.where(parent_uid: uids).pluck(:uid)
    end

    if @date.nil? # No date specified
      if feed_uids.empty?
        # No subscriptions, this is fairly meaningless
        @date = end_of_today
      else
        @date = Feed.where(uid: feed_uids).order("last_paper_date DESC").pluck(:last_paper_date).first
      end
    end

    if @range == :since_last
      @range, @since_last = _since_last_visit(@date)
    end

    @backdate = _backdate(@date, @range)
    @recent_comments = _recent_comments(feed_uids)

    if feed_uids.empty?
      # No subscriptions
      @papers = []
    else
      @papers, @pagination = _range_query(feed_uids, @backdate, @date, @page)
    end

    @scited_by_uid = current_user.scited_by_uid(@papers)

    render 'feeds/show'
  end

  # Showing a feed while we aren't signed in
  def show_nouser
    @feed = Feed.find_by_uid!(params[:feed])
    feed_uids = Rails.cache.fetch [:feed_uids, @feed] do
      [@feed.uid] + @feed.children.pluck(:uid)
    end

    if @date.nil?
      @date = @feed.last_paper_date
    end

    @backdate = _backdate(@date, @range)
    @recent_comments = _recent_comments(feed_uids)
    @papers, @pagination = _range_query(feed_uids, @backdate, @date, @page)

    render 'feeds/show'
  end

  # Showing a feed
  def show
    return show_nouser unless signed_in?

    @feed = Feed.find_by_uid!(params[:feed])

    feed_uids = Rails.cache.fetch [:feed_uids, @feed] do
      [@feed.uid] + @feed.children.pluck(:uid)
    end

    @recent_comments = _recent_comments(feed_uids)

    # If no date is specified, default to the last date
    # with available papers
    if @date.nil?
      @date = @feed.last_paper_date
    end

    if @range == :since_last
      @range, @since_last = _since_last_visit(@date)
    end

    @backdate = _backdate(@date, @range)

    @papers, @pagination = _range_query(feed_uids, @backdate, @date, @page)
    @scited_by_uid = current_user.scited_by_uid(@papers)

    render 'feeds/show'
  end

  private

  def parse_params
    @date = _parse_date(params)
    @range = _parse_range(params)
    @page = params[:page] || 1

    if signed_in?
      if @range.nil?
        @range = current_user.range_preference
        @range = :since_last if @range <= 0
      end
      range_num = @range == :since_last ? 0 : @range
      if range_num != current_user.range_preference && @date.nil?
        current_user.range_preference = range_num
        current_user.save!
      end
    else
      if @range.nil? || @range == :since_last
        # We don't know when the last value was here
        @range = 1
      end
    end
  end

  def _parse_date(params)
    date = params[:date] ? Chronic.parse(params[:date]) : nil
    return date
  end

  def _parse_range(params)
    return nil unless params.has_key?(:range)
    return :since_last if params[:range] == 'since_last'

    range = params[:range].to_i

    # negative date windows are confusing
    range = 0 if range < 0

    return range
  end

  # Calculate time range based on when they last visited this page
  def _since_last_visit(date)
    preferences = current_user.feed_preferences.where(feed_uid: params[:feed]).first_or_create(last_visited: date, previous_last_visited: date)

    if preferences.last_visited.end_of_day <= date.end_of_day - 1.day
      preferences.previous_last_visited = preferences.last_visited
      preferences.last_visited = date
      preferences.save!
    end

    since_last = date.end_of_day - preferences.previous_last_visited.end_of_day
    range = [1, (since_last / 1.day).round].max

    [range, since_last]
  end

  # Go range days back from a given date
  def _backdate(date, range)
    (date - (range-1).days)
  end

  def _recent_comments(feed_uids=nil)
    query = if feed_uids.nil?
      Comment.joins(:user, :paper)
             .where(deleted: false, hidden: false, hidden_from_recent: false)
    else
      Comment.joins(:user, paper: :categories)
             .where(deleted: false, hidden: false, hidden_from_recent: false)
             .where(categories: { feed_uid: feed_uids })
    end

    query.order('comments.id DESC')
         .limit(10)
         .select('DISTINCT ON (comments.id) comments.id',
                 'comments.content',
                 'comments.created_at',
                 'comments.updated_at',
                 'papers.uid AS paper_uid',
                 'papers.title AS paper_title',
                 'users.username AS user_username',
                 'users.fullname AS user_fullname')
  end

  # The primary SciRate query. Given a set of feed uids, a pair of dates
  # to look between, and a page number, find a bunch of papers and order
  # them by relevance.
  #
  # This can be an expensive query, particularly for large date ranges.
  # We optimize by delegating to Elasticsearch instead of Postgres, which
  # is better suited for these kinds of tag queries.
  def _range_query(feed_uids, backdate, date, page)
    page = (page.nil? ? 1 : page.to_i)
    per_page = 50

    filters = [
      {
        range: {
          pubdate: {
           from: backdate.beginning_of_day,
           to: date.end_of_day
          }
        }
      },
    ]

    filters << {terms: {feed_uids: feed_uids}} unless feed_uids.nil?

    query = {
      size: per_page,
      from: (page-1)*per_page,
      sort: [
        { scites_count: 'desc' },
        { comments_count: 'desc' },
        { pubdate: 'desc' },
        { submit_date: 'desc' },
        { uid: 'asc' }
      ],
      query: {
        filtered: {
          filter: {
            :and => filters
          }
        }
      }
    }

    res = Search::Paper.es_find(query)

    papers_by_uid = map_models :uid, Paper.where(uid: res.documents.map(&:_id))

    papers = res.documents.map do |doc|
      paper = papers_by_uid[doc[:_id]]

      paper.authors_fullname = doc.authors_fullname
      paper.authors_searchterm = doc.authors_searchterm
      paper.feed_uids = doc.feed_uids

      paper
    end

    pagination = WillPaginate::Collection.new(page, per_page, res.raw.hits.total)

    return [papers, pagination]
  end
end

app/views/feeds/_next_prev_links.html.slim
- @next_date = @date + @range.days
- @prev_date = @date - @range.days

- if @range == 1
  - @next_date += 2.days if @next_date.wday == 6
  - @next_date += 1.day if @next_date.wday == 0
  - @prev_date -= 2.days if @prev_date.wday == 0
  - @prev_date -= 1.day if @prev_date.wday == 6

nav.timenav
  h3 Date Published
  p style="text-align: center;"
    - if @range > 1
      | #{@backdate.strftime("%b %d %Y")} &mdash;
      =< @date.strftime("%b %d %Y")
      br
      | UTC
    - else
      = @date.strftime("%a %e %b %Y")
      br
      | UTC

  table cellspacing="0"
    tr
      td.btn-default.half.top.left
        a href=(url_for(params.merge(date: @prev_date.to_date, range: @range)))
          = "Prev #{@range == 1 ? 'day' : @range.to_s + ' days'}"
      td.btn-default.half.top.right
        a href=(url_for(params.merge(date: @next_date.to_date, range: @range)))
          = "Next #{@range == 1 ? 'day' : @range.to_s + ' days'}"

    tr
      td.underline


  table cellspacing="0"
    tr
      td.btn-default colspan="1" class=("btn-primary" if !@since_last && !params['date'] && @range == 1)
        a href=(url_for(range: 1)) 1d
      td.btn-default colspan="2" class=("btn-primary" if !@since_last && !params['date'] && @range == 3)
        a href=(url_for(range: 3)) 3d
      td.btn-default colspan="2" class=("btn-primary" if !@since_last && !params['date'] && @range == 7)
        a href=(url_for(range: 7)) 1w
      td.btn-default colspan="2" class=("btn-primary" if !@since_last && !params['date'] && @range == 31)
        a href=(url_for(range: 31)) 1m
      td.btn-default colspan="2" class=("btn-primary" if !@since_last && !params['date'] && @range == 365)
        a href=(url_for(range: 365)) 1y

  table
    tr
    - if signed_in?
      td.btn-default colspan="2" class=("btn-primary" if @since_last)
        a href=(url_for(range: 'since_last')) title="Shows papers you probably haven't seen before today, based on when you last visited." Recent
      td.btn-default colspan="2" class=("btn-primary" if false)
        a#customDate Custom

app/views/feeds/_subscribe.html.erb
<span class="subscribe-toggle <%= subscribed ? 'active' : '' %>" data-feed-uid="<%= feed.uid %>" data-feed-fullname="<%= feed.fullname %>">
  <button class="unsubscribe btn btn-success">
    Subscribed
  </button>

  <button class="subscribe btn btn-default">
    <i class="fa fa-sign-in"></i>
    Subscribe
  </button>
</span>

app/views/feeds/show.html.slim
- if @feed
  - title = @feed.fullname
- else
  - title = signed_in? ? "Home feed" : "Top arXiv papers"

- provide :title, title

.container#feed-page
  .row
    .col-md-2.feedbar
      ul.nav.nav-list.tree-sidebar
        = cache [:my_feeds, current_user, params.except(:feed, :page, :controller, :action)] do
          - if signed_in?
            li.feed-folder.my-feeds
              label.nav-header
                i.fa.fa-chevron-down
                = link_to("My feeds", feeds_path)
              ul.nav.nav-list.tree
                - if current_user.feeds.count == 0
                  li.leaf
                    = link_to("Add feeds", feeds_path)
                - else
                  - current_user.feeds.order(:fullname).each do |feed|
                    li.leaf title=(feed.uid)
                      = link_to(feed.fullname, feed_path(feed, params.except(:feed, :page, :controller, :action)))

        = cache [:sidebar, params] do
          li.source-heading arXiv.org
          - Feed.in_order(Settings::ARXIV_FOLDERS).each do |parent|
            li.feed-folder class=(@feed == parent ? 'active' : '') title=(parent.uid)
              - expanded = (@feed == parent || (@feed && @feed.parent == parent))
              label.nav-header
                i class=(expanded ? 'fa fa-chevron-down' : 'fa fa-chevron-right') class=(parent.children.length > 0 ? '' : 'transparent')
                = link_to parent.fullname.gsub("High Energy Physics", "HEP"), feed_path(parent, params.except(:feed, :page, :controller, :action))
              ul.nav.nav-list.tree style=(expanded ? '' : 'display: none;')
                - parent.children.each do |feed|
                  li.leaf class=(@feed == feed ? 'active' : '') title=(feed.uid)
                    = link_to(feed.fullname, feed_path(feed, params.except(:feed, :page, :controller, :action)))

    .col-md-10.feed-center
      - cache [:feed, @feed, current_user] do
        header.feed-header class=(@feed ? '' : 'home')
          .row
            - if @feed
              .col-md-10
                h1
                  = @feed.fullname
                  |  (#{@feed.uid})
              .col-md-2
                = render 'feeds/subscribe', feed: @feed, subscribed: signed_in? && @feed.subscriptions.exists?(user_id: current_user.id)
            - else
              .col-md-10
                h1= title
                - if signed_in?
                  = link_to "edit subscriptions", feeds_path, class: 'view-subs'
                - else
                  = link_to "sign in to customize", login_path, class: 'view-subs'
      .row
        .col-md-9
          .paperlist
            ul.papers
              - if @feed.nil? && signed_in? && !current_user.has_subscriptions?
                p.description
                  | New papers from all your subscribed feeds will appear here. You can find feeds to subscribe to using the links on the left, or by visiting the <a href="#{feeds_path}">my feeds</a> page.
              - elsif @papers.count == 0
                  p No papers found!
              - else
                - cache [:feed_papers, @papers.map { |paper| "#{paper.uid}/#{paper.scites_count}/#{paper.comments_count}" }] do
                  = render partial: "papers/paper", collection: @papers, as: :paper
                = will_paginate @pagination

        .col-md-3.feed-rightbar
          - cache [:next_prev, current_user, @feed, @date, @range, @backdate, @since_last]
            = render 'feeds/next_prev_links'
          - cache [:recent_comments, @recent_comments, current_user && current_user.can_moderate?] do
            - unless @recent_comments.length == 0
              h3
                - if @feed.nil?
                  a href=(comments_path) Recent comments
                - else
                  a href=(feed_comments_path(@feed)) Recent comments
              = render :partial => "comments/abbr_comment", :collection => @recent_comments